### ISSUE TITLE
result_evaluate  not recognizing True or False as a booleans

### ISSUE THREAD

**Issue by coneheadusa** [hpc/pavilion2#344]
In the  result_evaluate section  of one of my tests the following command sets the final results to  ERROR:
'result': 'gflops >= gflop_min' 

 'pav_result_errors': ["The value for the 'result' key in the results must be a boolean. Got '[False]' instead"],
 'pav_version': '2.2',
 'per_file': {},
 'result': 'ERROR',

where as this command  in another test sets the final results to either PASS/FAIL as expected.
 result: 'success == 5'
From the results.json file:
 "pav_result_errors": []

What am I doing incorrectly?

**Comment by nicholas-sly** [comment]
I've gotten the same issue very recently.  My issue was visible by seeing the entire results set (`pav results -f <test_id>`).  The issue was that (to adopt your variable names) 'gflops' was a list, and as such, Pavilion compares each element of the list and returns a list of results.  You have a couple of options.  If gflops is never going to contain more than one value, you can put `'result': 'gflops.0 >= gflop_min'`.  Alternatively, if gflops could potentially return more than one value, you can wrap the comparison in an `all()` or `any()` function (`pav show functions` for a list of available functions), depending on the behavior you'd like.  If your case doesn't fit either of these options, give me some more details and I'll try to come up with an option that'll work.

**Comment by coneheadusa** [comment]
Thank you for the prompt reply.  I have been reviewing the pav results -f <test_id> and experimenting with" pav results -r -L <test_id>” and did not notice that gflops was a list.  After modifying	 my test to use " gflops.0 >= gflop_min” the final result is set correctly.

Best regards,

Randy Smith

**Comment by Paul-Ferrell** [comment]
That's definitely a bug. I'll work on it today.

**Comment by coneheadusa** [comment]
My apologies,  I did see that gflops was a list, not a bug.

**Comment by Paul-Ferrell** [comment]
Yeah, I see now. Closing.
