### ISSUE TITLE
Feature request -  pav series run smoke_test -c <override.key>

### ISSUE THREAD

**Issue by coneheadusa** [hpc/pavilion2#707]
I would like the ability to use the -c OVERRIDES  functionality with "pav series run".   Is there is another method to accomplish this with the current release that I am not aware of?

One use case would be to use the -c to insert a included_nodes value i.e. "pav series run smoke_test -c schedule.include_nodes=node22"

Thanks.

**Comment by Paul-Ferrell** [comment]
I just checked, and you can already do that, at least in the latest master.

**Comment by coneheadusa** [comment]
Thank you, the -c option works as expected; however,   modules: ['intel/oneapi’, ‘intel/mpi/2021.10.0’]  entry in the test.yaml now produces a ModuleWrapperError: Invalid module name: ‘intel/mpi’.   The error is thrown for any module name of the form a/b/c.  The bug appears to be related the the number of ‘/‘ characters in the module name.

Randy

**Comment by Paul-Ferrell** [comment]
We changed module wrappers so you can just put them in configs rather than having to write plugins for them. Looks like we broke multi-level modulefiles.  I'll try to get that fixed quickly.

________________________________
From: Randy Smith ***@***.***>
Sent: Monday, September 25, 2023 11:45 AM
To: hpc/pavilion2 ***@***.***>
Cc: Ferrell, Paul Steven ***@***.***>; Comment ***@***.***>
Subject: [EXTERNAL] Re: [hpc/pavilion2] Feature request - pav series run smoke_test -c <override.key> (Issue #707)


Thank you, the -c option works as expected; however, modules: ['intel/oneapi’, ‘intel/mpi/2021.10.0’] entry in the test.yaml now produces a ModuleWrapperError: Invalid module name: ‘intel/mpi’. The error is thrown for any module name of the form a/b/c. The bug appears to be related the the number of ‘/‘ characters in the module name.

Randy

**Comment by coneheadusa** [comment]
Thanks for the quick response.   I was able to correct the problem by changing line 206 in module_wrapper.py  from
NAME_VERS_RE =  re.compile(r’^[a-zA-Z0-9_.*-]+$’) to NAME_VERS_RE =  re.compile(r’^[a-zA-Z0-9_.*-/]+$’).

Randy
